version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postmanager
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: node_container
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5433/postmanager
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
