FROM postgres:latest
#Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postmanager

#Copy te SQL to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/

